---
title: "effective_number_strays_note"
author: "Molly Payne"
date: "5/24/2022"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
This is the same document that can be found in "Chp1_analysis/docs" folder, FYI

The total effective number of strays column for a given stream-year in the 
new_response_var object (your new response variable as of May 2022) will not 
always equal the number of hatchery strays / proportion sampled for a stream-year because you set the proportions sampled that were greater than 1 equal to 1 instead. An example is Admiralty Creek 2009, which had 2 surveys:


```{r setup}
survey_data8 <- readRDS("survey_data8.rds")
survey_data8[survey_data8$StreamName == "Admiralty Creek" &
                   survey_data8$Year == "2009", c(2,3,18:30)]

new_response_var <- readRDS("new_response_var.rds")
new_response_var[new_response_var$StreamName == "Admiralty Creek" &
                   new_response_var$Year == "2009",]
```

The proportion sampled in Admiralty Creek in 2009 would be the sum( Number of 
Specimens) / sum (Dead Count ) for all the surveys (n = 2 in this case) in Admiralty
Creek in 2009. So, using the info in survey_data8, this would be
(96 + 21) / (117 + 14) = 117/131 = 0.89. Then, the total number of hatchery 
strays detected (39 + 9 = 48) should be divided by that proportion: 48 / 0.89 = 53.8 <br>

However, in new_response_var, the total_effective_strays in 2009 for Admiralty
Creek is 56.5, not 53.8. This is because for the second Admiralty Creek 2009
survey, the NumberofSpecimens was greater than the DeadCount, resulting in a
proportion sampled > 1. As per a decision made by Curry, Peter, and myself in 
April 2022, all proportions sampled > 1 were set equal to 1. So, the proportion
sampled for the second Admiralty Creek 2009 survey was reduced to 1, resulting
in the effective number of strays for the season being a little bit larger (bc
proportion sampled is the denominator when calculating effective strays, thus a
smaller denominator = large effective strays; 56.5 > 53.8)

